Repository KHU-Cloud-Project/Ameet-Server, pull requests merged in 2024-10, with the labels that each got.

#2 Chore : 기본 설정 파일 추가
  src/main/java/CloudProject/A_meet/global/config/SecurityConfig.java
  src/main/java/CloudProject/A_meet/global/config/SwaggerConfig.java
  src/main/java/CloudProject/A_meet/global/config/WebConfig.java
Labels: Chore 🧹

#7 [CI/CD] github actions workflow 파일 추가
  .github/workflows/main.yml
Labels: CI/CD 🌎

#8 [CI/CD] Dockerfile 추가
  Dockerfile
Labels: CI/CD 🌎

#5 [Feat] 유저 API 구현
  .gitignore
  src/main/java/CloudProject/A_meet/domain/group/domain/user/controller/UserController.java
  src/main/java/CloudProject/A_meet/domain/group/domain/user/domain/User.java
  src/main/java/CloudProject/A_meet/domain/group/domain/user/dto/UserLoginRequest.java
  src/main/java/CloudProject/A_meet/domain/group/domain/user/dto/UserResponse.java
  src/main/java/CloudProject/A_meet/domain/group/domain/user/dto/UserSignupRequest.java
  src/main/java/CloudProject/A_meet/domain/group/domain/user/repository/UserRepository.java
  src/main/java/CloudProject/A_meet/domain/group/domain/user/service/UserService.java
  src/main/java/CloudProject/A_meet/global/config/SecurityConfig.java
  src/main/java/CloudProject/A_meet/global/config/SwaggerConfig.java
  src/main/resources/application.yml
Labels: Feature✨
